language: android

jdk: oraclejdk8

android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - platform-tools
    - tools

    # The BuildTools version used by your project
    - build-tools-25.0.0

    # The SDK version used to compile your project
    - android-25

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    # - sys-img-armeabi-v7a-android-22
    # - sys-img-x86-android-17

script:
    - cd library
    - chmod u+x ./gradlew
    - ./gradlew clean assembleDebug
